### ISSUE TITLE
Incorrect CPP

### ISSUE THREAD

**Issue by hvr** [ekmett/semigroups#80] opened 2017-03-27 22:09 UTC
@RyanGlScott 

When compiling `semigroups-0.18.2` on GHC 7.6.3 w/ `bytestring-0.10.2.0` I run into the following compile failure:

```
Preprocessing library for semigroups-0.18.2..
Building library for semigroups-0.18.2..

src-ghc7/Data/Semigroup.hs:146:8:
    Could not find module `Data.ByteString.Short'
    It is a member of the hidden package `bytestring-0.10.8.1'.
    Perhaps you need to add `bytestring' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

after some investigation I found the culprit: 2d9fe673eabff3f69651a5093ff24d45be05ed73 introduced

```diff
 -# if MIN_VERSION_bytestring(0,10,4)
￼ +# if MIN_VERSION_bytestring(0,10,4) || defined(MIN_VERSION_bytestring_builder)
￼  import Data.ByteString.Short
￼  # endif
￼  #endif
```

```diff￼  
￼ -# if MIN_VERSION_bytestring(0,10,4)
￼ +# if MIN_VERSION_bytestring(0,10,4) || defined(MIN_VERSION_bytestring_builder)
￼  instance Semigroup ShortByteString where
￼    (<>) = mappend
￼  # endif
```

But  `defined(MIN_VERSION_bytestring_builder)` is not a sufficient condition for the existence of `Data.ByteString.Short`; `MIN_VERSION_bytestring(0,10,4)` however is.

**Comment by RyanGlScott** [comment] 2017-03-27 23:03
Something odd is going on here.

The `defined(MIN_VERSION_bytestring_builder)` bit _should_ be sufficient to conclude that `Data.ByteString.Short` exists; after all, the whole point of the `bytestring-builder` package is to backport `Data.ByteString.Short` and `Data.ByteString.Builder` when sufficiently old versions of `bytestring` are installed. And yet, that isn't happening for some reason. So my first inclination is to blame `bytestring-builder`.

Also, I can't reproduce the error you're getting. Here's the log I have from building with GHC 7.6.3 + `bytestring-0.10.2.0`:

```
$ cabal install --only-dependencies -w /opt/ghc/7.6.3/bin/ghc --constraint=bytestring==0.10.2.0
Resolving dependencies...
Notice: installing into a sandbox located at
/home/rgscott/Documents/Hacking/Haskell/semigroups/.cabal-sandbox
Downloading bytestring-0.10.2.0...
Configuring transformers-0.5.4.0...
Building transformers-0.5.4.0...
Configuring bytestring-0.10.2.0...
Building bytestring-0.10.2.0...
Installed transformers-0.5.4.0
Configuring transformers-compat-0.5.1.4...
Building transformers-compat-0.5.1.4...
Installed transformers-compat-0.5.1.4
Configuring tagged-0.8.5...
Building tagged-0.8.5...
Installed tagged-0.8.5
Installed bytestring-0.10.2.0
Downloading bytestring-builder-0.10.4.0...
Configuring binary-0.8.2.1...
Building binary-0.8.2.1...
Configuring bytestring-builder-0.10.4.0...
Building bytestring-builder-0.10.4.0...
Installed binary-0.8.2.1
Configuring text-1.2.2.1...
Building text-1.2.2.1...
Installed bytestring-builder-0.10.4.0
Installed text-1.2.2.1
Configuring hashable-1.2.6.0...
Building hashable-1.2.6.0...
Installed hashable-1.2.6.0
Configuring nats-1.1.1...
Configuring unordered-containers-0.2.8.0...
Building nats-1.1.1...
Building unordered-containers-0.2.8.0...
Installed nats-1.1.1
Installed unordered-containers-0.2.8.0
rgscott@gearloose:~/.../Hacking/Haskell/semigroups$ cabal configure -w /opt/ghc/7.6.3/bin/ghc --constraint=bytestring==0.10.2.0
Resolving dependencies...
Configuring semigroups-0.18.2...
rgscott@gearloose:~/.../Hacking/Haskell/semigroups$ cabal build
Building semigroups-0.18.2...
Preprocessing library semigroups-0.18.2...

src-ghc7/Data/Semigroup.hs:146:18:
    Ambiguous module name `Data.ByteString.Builder':
      it was found in multiple packages:
      bytestring-0.10.2.0 bytestring-builder-0.10.4.0
```

Which is arguably just as bad, because now `bytestring-builder` is defining `Data.ByteString.Builder` when it shouldn't!

**Comment by RyanGlScott** [comment] 2017-03-27 23:05
Oh, here's something interesting. Pretty much every version of `bytestring-builder` has version bounds on `bytestring` to the effect of `>=0.9 && <0.10.2 || >=0.10.4`. This contributes to the wacky build plan seen above when `bytestring-0.10.2.0` is chosen (in fact, `cabal` picked `bytestring-builder-0.10.4.0`, which has been deprecated!).

@lpsmith, do you have any thoughts on why the version bounds for `bytestring-builder` are like this?

**Comment by hvr** [comment] 2017-03-28 06:50
@RyanGlScott in case you want to reproduce my original compile error, I've generated a `cabal.project.freeze` file (via `new-freeze`):

```
with-compiler: ghc-7.6.3
constraints: Cabal ==1.24.2.0,
             Cabal -bundled-binary-generic,
             array ==0.4.0.1,
             base ==4.6.0.1,
             binary ==0.8.2.1,
             bytestring ==0.10.2.0,
             bytestring-builder ==0.10.4.0,
             bytestring-builder +bytestring_has_itoa_c +bytestring_has_builder,
             containers ==0.5.0.0,
             deepseq ==1.3.0.1,
             directory ==1.2.0.1,
             filepath ==1.3.0.1,
             ghc-prim ==0.3.0.0,
             hashable ==1.2.6.0,
             hashable -sse41 +sse2 +integer-gmp -examples,
             integer-gmp ==0.5.0.0,
             nats ==1.1.1,
             nats +template-haskell +hashable +binary,
             old-locale ==1.0.0.5,
             old-time ==1.1.0.1,
             pretty ==1.1.1.0,
             process ==1.1.0.2,
             rts ==1.0,
             semigroups +unordered-containers +transformers +text +tagged +hashable +deepseq +containers +bytestring-builder +bytestring +binary,
             tagged ==0.8.5,
             tagged +transformers +deepseq,
             template-haskell ==2.8.0.0,
             text ==1.2.2.1,
             text -integer-simple -developer,
             time ==1.4.0.1,
             transformers ==0.5.4.0,
             transformers-compat ==0.5.1.4,
             transformers-compat -two -three +mtl,
             unix ==2.6.0.1,
             unordered-containers ==0.2.8.0,
             unordered-containers -debug
```

**Comment by hvr** [comment] 2017-03-28 07:02
@RyanGlScott btw, are you saying we should make sure that those 2 deprecated `bytestring-builder` packages never got picked by the cabal solver by hard-blacklisting them via editing in a `build-depends: base<0` contradiction?

**Comment by RyanGlScott** [comment] 2017-03-28 13:05
> btw, are you saying we should make sure that those 2 deprecated `bytestring-builder` releases never get picked by the cabal solver by hard-blacklisting them via editing in a build-depends: `base<0` contradiction?

I don't think that would help much in this scenario. The problem is, as far as I can see, that _all_ (non-deprecated) releases of `bytestring-builder` rule out `bytestring-0.10.2.0` through restrictive version bounds. So even if we hard-blacklisted the the deprecated releases, that would just cause `cabal-install` to conclude that there are no valid install plans, right?

I can't help but wonder what the reasoning is behind excluding `bytestring-0.10.2` is in `bytestring-builder`'s version bounds (e.g., `>=0.9 && <0.10.2 || >=0.10.4`). @lpsmith, perhaps you might be able to impart some wisdom about this?

**Comment by lpsmith** [comment] 2017-03-29 00:32
Because for reasons I don't quite recall off the top of my head,  bytestring-builder cannot support bytestring 0.10.2.   There was some kind of export problem where the bytestring-builder modules were present,  and the haddocks made it look like a bunch of stuff was exported,  but the modules didn't actually export anything.  And maybe some other reasons.

**Comment by lpsmith** [comment] 2017-03-29 00:33
In my opinion,  bytestring-0.10.2 itself should be deprecated.

**Comment by hvr** [comment] 2017-03-29 07:43
As a first short-term measure I've propagated bytestring-builder-0.10.4.0.1 tighter constraints to bytestring-builder-0.10.4.0 ; this should at the very least make sure that there is no release of bytestring-builder that allows bytestring-0.10.2.* (and given bytestring-builder is quite popular, that'll result in bytestring-0.10.2 being indirectly excluded by most install-plans)

**Comment by phadej** [comment] 2019-01-26 23:35
I think this issue is resolved. If `bytestring-builder` contract is to **always** make `Data.ByteString.Short` available, problem was there; and not it's resolved.

**Comment by phadej** [comment] 2022-08-21 10:00
based on my previous comment this issue can be closed.

**Comment by RyanGlScott** [comment] 2022-08-21 11:08
Closing per https://github.com/ekmett/semigroups/issues/80#issuecomment-457875503.

**Closed by RyanGlScott** 2022-08-21 11:08 UTC
